export * from "./Home";
export * from "./About";
export * from "./Contatti";
export * from "./Products";
export * from "./Cart";
export * from "./ProductId";
export * from "./Login";
export * from "./Profile";
export * from "./Checkout";
export * from "./Shipping";
export * from "./Payment";
// export * from "./Confirmation";
